### ISSUE TITLE
Requires the ability to display a heat map from Monday

### ISSUE THREAD

**Issue by reysonk** [mudkipme/MoeMemosAndroid#100]
Is your feature request related to a problem?

Requires the ability to display a heat map from Monday

Describe the solution you'd like

The switch in the menu that changes the first day is Monday\Sunday

![изображение](https://github.com/mudkipme/MoeMemosAndroid/assets/26927358/0c900c2c-47e9-456b-8818-f2938658b02c)

**Comment by mudkipme** [comment]
It seems Moe Memos does respect the locale settings of Android system. So if you choose a language/locale where Monday is the first, the heat map does start with Monday.

However, there is a bug with the weekday text displayed on left side, it's always starts with Sunday and may indicates the wrong date. This will be fixed.

BTW, the app also already supports Android 14's regional preference feature so it's possible to set first day of week without changing locale.
