### ISSUE TITLE
add ko-fi on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [mudkipme/MoeMemosAndroid#106]
@mudkipme 
* **your explicit consent is required** to add ko-fi ```https://ko-fi.com/mudkipme``` given at https://github.com/mudkipme/MoeMemosAndroid/ #Sponsor this project in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/me.mudkip.moememos.yml)
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by mudkipme** [comment]
Thanks for reminding!

I'm glad that the ko-fi link `https://ko-fi.com/mudkipme` can be added to Moe Memos' fdroid metadata.
