### ISSUE TITLE
update FDroid release

### ISSUE THREAD

**Issue by coding-lemur** [mudkipme/MoeMemosAndroid#115]
Hey. Yesterday I found your great app and installed via FDroid store.
I noticed that the I unable to login to current memos Server (0.15.x). After Github recherche I found that on FDroid is only the old version 0.7 available. Maybe you can update the FDroid releases :)

best regards

René

**Comment by mudkipme** [comment]
The [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/me.mudkip.moememos.yml) of Moe Memos in F-Droid is already updated and 0.7.1 is built successfully according to [F-Droid Monitor](https://monitor.f-droid.org/builds/running).

Typically it takes 3-7 days for F-Droid to have latest version. Moe Memos uses [Reproducible Builds](https://f-droid.org/docs/Reproducible_Builds/) so you can freely update from F-Droid version to the GitHub release version, or vice versa.
