### ISSUE TITLE
请问Play商店版是停更了吗？

### ISSUE THREAD

**Issue by erbanku** [mudkipme/MoeMemosAndroid#136]
如题

有一段时间用不了，Play版迟迟不更新。今天从官网下载新版apk文件解决了。

**Comment by mudkipme** [comment]
The Google Play version is up to date at https://play.google.com/store/apps/details?id=me.mudkip.moememos.

If you installed Moe Memos via GitHub or F-Droid first, Play Store won't upgrade the app because the Play Store version is signed by Google. (GitHub and F-Droid versions are identical.)
