### ISSUE TITLE
network

### ISSUE THREAD

**Issue by ikum852** [mudkipme/MoeMemosAndroid#139]
Why can Moememos create and edit notes for my IPv6 server in an IPv4 environment? Did it use your server?

**Comment by mudkipme** [comment]
Moe Memos can only connect to your Memos server directly and no other network connection is possible.

It is possible your IPv6 server has IPv4 addresses, or your network environment does actually support IPv6. For example, you may connect to an IPv4 only Wi-Fi but your LTE network has IPv6.
