### ISSUE TITLE
java.security.cert.certpathvalidatorexception trust anchor for certification path not found

### ISSUE THREAD

**Issue by maodaisuki** [mudkipme/MoeMemosAndroid#147]
The memos site is using certification provided by freeSSL.cn, and this error occurs when I try to log in.
![Screenshot_20240129_172608.jpg](https://github.com/mudkipme/MoeMemosAndroid/assets/133942310/46faa018-e921-468f-ada9-b3be83c64305)

**Comment by mudkipme** [comment]
Please try visiting your Memos instance with the default browser on your Android device and test whether there's the same issue.

Using full chain (filename should be similar to `fullchain.pem`) instead of standalone certificate file in your server config may also help resolving this issue.

**Comment by maodaisuki** [comment]
I tried to use full chain instead of standalone certificate file. It worked. Thank you very much.
