### ISSUE TITLE
Android app doesnt display images

### ISSUE THREAD

**Issue by n1njaznutz** [mudkipme/MoeMemosAndroid#150]
Moe Memos : Android version 0.7.2
Memos : Version 0.19.1
Storage : via PostgreSQL database

Not sure if this normal behaviour when Memos Current Object Storage is other than Local file system (in my case its via PostgreSQL dB), however, I am not seeing images in app (in any view) - I can add/upload and they are visible in Memos, just not in the App - although placeholders are created for images - see screenshot.

Not sure if this normal behaviour - if it is, is it resolved/changed in version 2 (which I see is in development)?

Many thanks

![Screenshot_20240205_115703_MoeMemos~2](https://github.com/mudkipme/MoeMemos/assets/150074096/5dce2266-11e6-4c98-9c91-6d89b31d4a31)

**Comment by mudkipme** [comment]
Thanks for the information. There is a compatibility issue with Memos 0.19.0 or later. It will be fixed in next patch version. 😃

**Comment by n1njaznutz** [comment]
That's excellent news! Thank you. I will patiently await the patch update 🙂🙏
