### ISSUE TITLE
can't display picture

### ISSUE THREAD

**Issue by yzmninglang** [mudkipme/MoeMemosAndroid#163]
I tried to use the app to add pictures, but the pictures could not be displayed. I also checked the storage permissions, but it showed that the app does not require storage permissions.The image display on the web page is normal.app is the latest version(0.7.3)

![WZXCYL)T0CERL3(6CP0CXFV](https://github.com/mudkipme/MoeMemosAndroid/assets/43769513/04b08ff5-68be-4374-bd54-c66e37ec0b3a)

Device model: OnePlus ace2pro
Android: 13

**Comment by mudkipme** [comment]
Please remind that Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.20.1`.

Memos 0.21 will be supported by Moe Memos ASAP *after* it is released.

**Comment by aleprovencio** [comment]
I'm still having this issue on `0.8.1`
`0.8.2` is not on `fdroid` yet
