### ISSUE TITLE
can't login in  with Memos 0.22.0

### ISSUE THREAD

**Issue by wander555** [mudkipme/MoeMemosAndroid#175]
user not found with username....
success through the web...

**Comment by mudkipme** [comment]
Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.21.0`.

You can check the latest version of Memos at https://github.com/usememos/memos/releases.

New release of Memos will be supported by Moe Memos ASAP *after* it is released.

**Comment by wander555** [comment]
> Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.21.0`.
> 
> You can check the latest version of Memos at https://github.com/usememos/memos/releases.
> 
> New release of Memos will be supported by Moe Memos ASAP _after_ it is released.
all right...thanks
