### ISSUE TITLE
user not found with username 

### ISSUE THREAD

**Issue by odtu945** [mudkipme/MoeMemosAndroid#176]
以下是优化后的内容及中英文版本：

**中文描述**：

memos 版本：v0.22.0

MoeMemosAndroid 版本：0.7.4

我通过 docker 自行部署了 memos 服务，然后在安卓手机上使用 MoeMemosAndroid 进行内容的编写和查看，它一直以来都给我带来了极大的便利。然而，最近这套软件出现了异常，账户自动退出登录了。当我再次使用账号密码登录时，却提示“user not found with username”，但我用相同的用户名和密码在浏览器上却能够正常登录。

非常感谢您所做的伟大工作，给您添麻烦了。

**英文描述**：

Version of memos: v0.22.0

Version of MoeMemosAndroid: 0.7.4

I deployed a set of memos services using docker myself, and then used MoeMemosAndroid on my Android phone to write and view the content, which has brought me great help all the time. However, recently, there was an abnormality in this software, and the account automatically logged out. When I tried to log in again using the account password, it was prompted "user not found with username", but I could log in normally on the browser with the same username and password.

Thank you very much for your great work, and I'm sorry to trouble you.
![微信图片编辑_20240517091243](https://github.com/mudkipme/MoeMemosAndroid/assets/12626706/cd8b398d-c569-4bd7-bba3-36bcd4fa6da1)

**Comment by mudkipme** [comment]
Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.21.0`.

You can check the latest version of Memos at https://github.com/usememos/memos/releases.

New release of Memos will be supported by Moe Memos ASAP *after* it is released.

**Comment by mowic** [comment]
I met the same issue

**Comment by odtu945** [comment]
> Moe Memos doesn't support pre-release versions of Memos, as their APIs are unstable and may subject to change. If you are using Docker with Memos, please use `stable` tag or pin the version to `0.21.0`.
> 
> You can check the latest version of Memos at https://github.com/usememos/memos/releases.
> 
> New release of Memos will be supported by Moe Memos ASAP _after_ it is released.

Thank you so much for your prompt response. My issue has been resolved according to your reply. Appreciate your efforts and assistance. Have a great day!

**Comment by CodingEmil** [comment]
I am having the same issue. App version is: 0.7.4 and Memos is running the stable image (v0.22.1).

**Comment by mudkipme** [comment]
Please download the [latest pre-release version](https://github.com/mudkipme/MoeMemosAndroid/releases) if you are using Memos 0.22.0 or higher.

**Comment by betterthanever2** [comment]
> Please download the [latest pre-release version](https://github.com/mudkipme/MoeMemosAndroid/releases) if you are using Memos 0.22.0 or higher.

When, do you think support for `0.22` would be added?
