### ISSUE TITLE
Cannot sign in using access token - Help needed

### ISSUE THREAD

**Issue by silversurfer98** [mudkipme/MoeMemosAndroid#179]
I've been using Authelia SSO for user management within Memos, and accessing the app through token sign-in. This method was functioning perfectly until a week ago when all tokens were unexpectedly erased from the Memos server. So, I generated a new token set to never expire and attempted to sign in using the same process as before in the app. However, it's not working, and no error message is displayed, as shown in the attached image. Could I be missing something here? 
P.S The web version is operating correctly, and Authelia authentication is also in good order.
I even tried the demo memos server [link](https://demo.usememos.com/setting) but same results in app.
### this is my memos server logs
```logs
memos    | ---
memos    | Server profile
memos    | version: 0.22.0
memos    | data: /var/opt/memos
memos    | dsn: postgresql://user:pass@postgres:5432/memos?sslmode=disable
memos    | addr: 
memos    | port: 5230
memos    | mode: prod
memos    | driver: postgres
memos    | ---
memos    | Version 0.22.0 has been started on port 5230
memos    | ---
memos    | See more in:
memos    | 👉Website: https://usememos.com
memos    | 👉GitHub: https://github.com/usememos/memos
```

![image](https://github.com/mudkipme/MoeMemosAndroid/assets/29462039/151bad24-d393-41cd-ba14-8c4cfa4045a4)

Kindly help me on this situation. Thanks in advance

**Comment by mudkipme** [comment]
Moe Memos doesn't support Memos 0.22.0 yet. Due to major API-breaking changes, it may take longer to release a compatible version.

**Comment by silversurfer98** [comment]
Thank you pointing this out, I will downgrade my memos server, And let me mark this as closed
