### ISSUE TITLE
INVALID SERVER: Fails to sign in

### ISSUE THREAD

**Issue by mizzunet** [mudkipme/MoeMemosAndroid#181]
![Screenshot_20240604-215432_MoeMemos](https://github.com/mudkipme/MoeMemosAndroid/assets/10193999/66aadcb2-de0a-481e-a39b-77a1f9805136)

Log in console
```
2024/06/04 16:24:29 ERROR: Failed to extract ServerMetadata from context
```

MoeMemos: 0.8.0
memos: 0.22.1

**Comment by mudkipme** [comment]
Please reply with the response of `http://127.0.0.1:8081/api/v1/workspace/profile`.

As you are using 127.0.0.1 as the host, did you run Memos on the local Android device (such as via Termux)? If not, you need to use the actual server address.

**Comment by mudkipme** [comment]
Can you visit http://127.0.0.1:8081/api/v1/workspace/profile with your browser on the Android device and reply with the content?

**Comment by mudkipme** [comment]
> ```
> {
>   "code": 14,
>   "message": "name resolver error: produced zero addresses",
>   "details": []
> }
> ```

This error is happened in https://github.com/grpc/grpc-go/blob/v1.64.0/pickfirst.go#L92. It seems the grpc gateway in Memos can't connect to the internal grpc server.

Do you have any specific command or environment variables to run Memos? I followed the guide on https://github.com/memospot/memos-builds?tab=readme-ov-file#running-on-android and didn't find any issues.

**Comment by n00b12345** [comment]
I'm facing the same issue even on a remote server. It used to work fine, till I had to restore my memos server from a backup.
