### ISSUE TITLE
0.8.0安卓移动端无法展示图片

### ISSUE THREAD

**Issue by fengshenshao** [mudkipme/MoeMemosAndroid#183]
客户端使用0.8.0安卓版本，docker部署版本0.22.2
问题：手机客户端选取照片或用手机拍照上传图片时，没有反应，输入文字提交后，点击内容有图片的占位，但图片不展示，网页登录服务器，显示图片已经上传成功，但客户端还是无法展示，同样在网页端上传图片附件，移动端也无法展示

**Comment by mudkipme** [comment]
Memos 0.22.1 introduced an API change in https://github.com/usememos/memos/blob/v0.22.1/proto/api/v1/resource_service.proto#L38 which is not supported by Moe Memos yet.
