### ISSUE TITLE
user not found with username...

### ISSUE THREAD

**Issue by cortomalese** [mudkipme/MoeMemosAndroid#188]
Hi, I'd installed memos via docker container, but I can't login. I got 
> user not found with username...
This is the response of http://192.168.xx.xx:5230/api/v1/workspace/profile :
> {"owner":"", "version":"0.22.2", "mode":"prod"}
Where can I introduce username and password?
Thanks

**Comment by mudkipme** [comment]
Please try login with access token if you have any problem logging-in with username/password. Access tokens can be copied from Memos setting page.

**Comment by cortomalese** [comment]
I built the container via Portainer. I rebuilt it by hand and everything works fine.
Thank you very much for your help.
