### ISSUE TITLE
[Feature]Stylus input in text fields

### ISSUE THREAD

**Issue by sicl5300** [mudkipme/MoeMemosAndroid#193]
Stylus input in text fields are introduced in Android 14, allowing pen users to actually "write" text into input field.

This is a pretty new feature so I'm worrying about the difficulty in implementing it, hope it can be supported :)

- <https://developer.android.com/develop/ui/views/touch-and-input/stylus-input>
- <https://developer.android.com/develop/ui/views/touch-and-input/stylus-input/stylus-input-in-text-fields>

**Comment by mudkipme** [comment]
According to https://developer.android.com/develop/ui/compose/touch-input/stylus-input/stylus-input-in-text-fields, the only thing needed is upgrading Jetpack Compose to 1.7.0 😄
