### ISSUE TITLE
Tags used in private memos only are visible to other users

### ISSUE THREAD

**Issue by bustikiller** [mudkipme/MoeMemosAndroid#204]
Good morning!

I have recently reported an issue in memos' GitHub repository regarding the visibility of tags used only in private memos. Full context is available at https://github.com/usememos/memos/issues/3899

We would like to involve MoeMemos' maintainers in the conversation to discuss where it makes the most sense to fix this issue (in the server or the client). In order to keep a single thread of discussion, I would suggest that we continue the thread opened in the issue linked above, but that's just my suggestion.

Thanks!

**Comment by MaudGuan** [comment]
我也遇到了同样的问题，任何一个成员都能看到所有成员的标签

**Comment by mudkipme** [comment]
Memos 0.23.0 no longer has dedicated API for tags. So this will no longer be an issue.
