### ISSUE TITLE
Reverse proxy and https

### ISSUE THREAD

**Issue by hiddenbar10** [mudkipme/MoeMemosAndroid#208]
I create a memos  server on Synology Nas，and I use reverse proxy to trans http into https. I can access to memos through browsers，but when I try to login memos with https through moeMemos，it displayed：“invalid server”. After that，I set the protocols on both ends of the reverse proxy server to http，and I successfully login in memos through moeMemos.
It seems like moeMemos doesn't support https？

**Comment by jkuhlemann** [comment]
I have no issues connecting to my Memos Host via HTTPS. I'm wondering what the issue might be, but I'm pretty sure that the app is not the problem in this case.

**Comment by hiddenbar10** [comment]
Thanks for your reply, now I know why. I did not add an ssl certificate for my server, this problem solved after I added an ssl certificate for my server, now I can connecting to my Memos Host via HTTPS with domain on the public network. Thanks again.
