### ISSUE TITLE
Image not visible in App

### ISSUE THREAD

**Issue by Tiboriuss** [mudkipme/MoeMemosAndroid#209]
Hello i am using the latest version available on F-Droid. I'm logging into Memos via Authentik SSO. When i make a Memo with a Image, i can post it. The picture then is visible on the webinterface but not in the app. When i click on pin post in the app, the image is visible but cannot be opened. The image will disappear after clicking something else then the post.

**Comment by TheLux83** [comment]
I just wanted to say, that I have the same issue.
But I'm not using any SSO but the normal login tool.
The rest is the same here.
I'm using the App version 0.8.2 and Memos in version 0.23.0

**Comment by mudkipme** [comment]
Fixed with #217
