### ISSUE TITLE
Add todo items to list

### ISSUE THREAD

**Issue by Aamon-Magnusson** [mudkipme/MoeMemosAndroid#21]
Hello, thank you for the work on this application.

While I do appreciate being able to cross items off of a todo list, I would also like to be able to add to them easily.

In the desktop memos standard web interface there is a button to create a new check box, where that seems to be missing here.

Preferably it would be nice to be able to press enter and another check box will be created, but one thing at a time.

I would like to help out, however I am not a dev, nor do I know anything in Kotlin or Jetpack Compose.

I hope this is not too much to ask, thank you for your time.

**Comment by mudkipme** [comment]
Thanks for your suggestions!

I do plan to add buttons in the bottom toolbar of memo composing screen to create to-do list or other markdown syntax and allowing creating new to-do item by pressing enter.

It would take longer as I'm going through COVID 😷

**Comment by Aamon-Magnusson** [comment]
Take your time to get better, and thank you again.
