### ISSUE TITLE
Add local functions.

### ISSUE THREAD

**Issue by amokiel** [mudkipme/MoeMemosAndroid#22]
I prefer to use local services with backup capabilities. Hopefully developers will consider native features. Thanks for your hard work

**Comment by ServerGeek82** [comment]
So basically local caching of the memos on the mobile app when not connected?

**Comment by ServerGeek82** [comment]
I did find out that I couldn't see the memos unless connected. Local caching of the notes or memos can't be displayed unless connected to the server.
