### ISSUE TITLE
Compact View

### ISSUE THREAD

**Issue by lokesh-krishna** [mudkipme/MoeMemosAndroid#32]
Fantastic job on the Markdown headings :D They're a treat! 

Would you consider adding an optional compact view? Presently, the list view shows the entirety of each note and this results in a lot of scrolling if even a single long note is involved. The compact view could just show the first line of a note along with date and/or tags.

**Comment by mudkipme** [comment]
Thanks for the idea! I will explore how to implement compact view 😄 

I also found the web version of Memos supports separating long memo by `---` (not available in Moe Memos yet)

**Comment by lokesh-krishna** [comment]
Thanks for considering it! Would love to have a way to donate or support. This app has been a real gem!

**Comment by lokesh-krishna** [comment]
Just for the sake of discussion, I feel like supporting a compact view on its own and folding memos from the web version (`---`) would be tricky and that it might be better to just support the folding memos feature directly.
