### ISSUE TITLE
Upload photos not working

### ISSUE THREAD

**Issue by adapdesign** [mudkipme/MoeMemosAndroid#33]
Not able to upload images, API returns error

```
POST "/api/resource"
Malformatted post resource request
```

Switching to `/api/resource/blob` seems to fix the issue

EDIT log from my memos server:
```
method=POST uri=/api/resource status=400 error=code=400, message=Malformatted post resource request, internal=invalid character '-' in numeric literal
```

**Comment by mudkipme** [comment]
Thanks for pointing out and pull request!

Memos 0.10.2 changed the resource uploading endpoint to `/api/resource` to `/api/resource/blob`. I also documented recent server API change and supported app version here: https://memos.moe/memos/

**Comment by mudkipme** [comment]
0.5.2 is released! 🎉
