### ISSUE TITLE
Link in MoeMemos renders strange

### ISSUE THREAD

**Issue by qrzbing** [mudkipme/MoeMemosAndroid#43]
I write a link in Memos:

``` markdown
[[TEST] Google](https://www.google.com/)
```

and it will render like this on web page:

![image](https://user-images.githubusercontent.com/23500397/220584410-ebaea89d-b1fc-4512-bcbc-7834a855d90d.png)

but in MoeMemos, characters after right bracket are lost:

![image](https://user-images.githubusercontent.com/23500397/220584860-fd8d7320-086f-4082-b614-1434bb041002.png)

**Comment by mudkipme** [comment]
This is fixed with 0.5.4
