### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [mudkipme/MoeMemosAndroid#47]
The apk is not reproducible. Maybe we build it from different commits?

[diff.zip](https://github.com/mudkipme/MoeMemosAndroid/files/10837811/diff.zip)

**Comment by mudkipme** [comment]
I've cleared build cache and recreated a signed APK. Let's see whether it's reproducible this time.

I guess it's caused by some build cache of my Android Studio, the upgraded Android Gradle plugin, or Kotlin version.

**Comment by linsui** [comment]
It works, thanks!
