### ISSUE TITLE
New tag does not appear in the tag list

### ISSUE THREAD

**Issue by qrzbing** [mudkipme/MoeMemosAndroid#54]
MoeMemosAndroid and MoeMemos will not add new tag to Memos tag list when adding new Memos (which have tags). I try to capture the network package and found:

When using the web page to publish memo, its behavior is `POST /api/memo`, and then `POST /api/tag` for the tags you added. But the behavior of the MoeMemos client is only the previous one, that is, only `POST /api/memo`. https://github.com/usememos/memos/issues/1310#issuecomment-1465986967

How can I help to fix it? I found `MemoInputPage.kt:MemoInputPage:submit` in MoeMemosAndroid:

```kotlin
    fun submit() = coroutineScope.launch {
        memo?.let {
            viewModel.editMemo(memo.id, text.text).suspendOnSuccess {
                navController.popBackStack()
            }.suspendOnErrorMessage { message ->
                snackbarState.showSnackbar(message)
            }
            return@launch
        }

        viewModel.createMemo(text.text).suspendOnSuccess {
            text = TextFieldValue("")
            viewModel.updateDraft("")
            navController.popBackStack()
        }.suspendOnErrorMessage { message ->
            snackbarState.showSnackbar(message)
        }
    }
```

which will only call `editMemo` or `createMemo` method. But when I read memos web src, I found it upsert new tag after create or edit memos (in `web/src/components/MemoEditor.tsx:handleSaveBtnClick`): https://github.com/usememos/memos/blob/ca6839f59399d02723b9dce43ab3d6ee8cc98490/web/src/components/MemoEditor.tsx#L276

Do we need to accomplish a similar behavior like memos web API? I'm not sure if I can update tags in submit method, and I'm glad to add this feature after discussing with you.

**Comment by qrzbing** [comment]
In `web/src/components/MemoEditor.tsx:handleSaveBtnClick`, Memos Web `getMatchedNodes` from content.
```ts
    // Upsert tag with the content.
    const matchedNodes = getMatchedNodes(content);
    const tagNameList = uniq(matchedNodes.filter((node) => node.parserName === "tag").map((node) => node.matchedContent.slice(1)));
    for (const tagName of tagNameList) {
      await tagStore.upsertTag(tagName);
    }
```

`getMatchedNodes` match nodes by some rules defined in `web/src/labs/marked/parser/`, and what we interested in is `web/src/labs/marked/parser/Tag.tsx`. It extracts tags by regular expression `/#([^\s#]+)/`. 

I have added some code to update tags, but I don't find a good expression which can find all tags. Thanks if somebody could help me!

**Comment by qrzbing** [comment]
When I test a case like this:

```
#111 #222 #测试 #cs 测试
```

It can not identify chinese tags and English tags.
![image](https://user-images.githubusercontent.com/23500397/224764570-d8004ef2-3d72-4551-9595-20ee2b4e97db.png)

**Comment by qrzbing** [comment]
> Thanks for the discussion!
> 
> One thing we need to take into account is `#` mark in certain Markdown elements (code block, links, images, etc) should be avoided. I guess it could be done with [intellij-markdown](https://github.com/JetBrains/markdown).
> 
> Or I wonder whether it's possible extend `intellij-markdown` to support tags in a native way. (That will let memo card render tags too)

Yes, you are right, I forget `#` is widely used in different elements. I have some questions about where to parse markdown elements in `MemoInputPage.kt:submit`. I find `Markdown` is used in `Memocard.kt`, but we may analyze markdown elements in submit method?

For I have accomplish updateTag API (it is easy) and not sure how to accomplish parser, can I take a pr for only updateTag API or accomplish all features? I'm not a Android developer, and I'm a new hand in open source contribution. Thank you!

**Comment by mudkipme** [comment]
> > Thanks for the discussion!
> > One thing we need to take into account is `#` mark in certain Markdown elements (code block, links, images, etc) should be avoided. I guess it could be done with [intellij-markdown](https://github.com/JetBrains/markdown).
> > Or I wonder whether it's possible extend `intellij-markdown` to support tags in a native way. (That will let memo card render tags too)
> 
> Yes, you are right, I forget `#` is widely used in different elements. I have some questions about where to parse markdown elements in `MemoInputPage.kt:submit`. I find `Markdown` is used in `Memocard.kt`, but we may analyze markdown elements in submit method?
> 
> For I have accomplish updateTag API (it is easy) and not sure how to accomplish parser, can I take a pr for only updateTag API or accomplish all features? I'm not a Android developer, and I'm a new hand in open source contribution. Thank you!

Thanks! It's super welcome for any contribution and it's not required to be feature completed 😆 

For reference, the parser used by `MemosCard` is https://github.com/mudkipme/MoeMemosAndroid/blob/main/app/src/main/java/me/mudkip/moememos/ui/component/Markdown.kt#L41
