### ISSUE TITLE
Tags don't register at end of memo

### ISSUE THREAD

**Issue by deansallinen** [mudkipme/MoeMemosAndroid#6]
If I'm writing a memo with a tag at the end, the tag isn't activated unless there's a following character (like a trailing space).

For example, "This is my memo #tagone #tagtwo" will activate #tagone but not #tagtwo. 

If you add a trailing space, e.g. "This is my memo #tagone #tagtwo " now both tags will be active.

**Comment by mudkipme** [comment]
Seems it's by design on server side according to https://github.com/usememos/memos/issues/137
