### ISSUE TITLE
Newline copy world

### ISSUE THREAD

**Issue by bonnebulle** [mudkipme/MoeMemosAndroid#63]
Hello thanks to make memos much better with this app !
Am on android 11
Last version of MoeMemos installed (0.6.0)
My memos self hosted is on last too !

When am typing and hit Enter to break a line the last word is copied on the new line !
Very enoying
Very but works if I add a Space at the end of my line
![Screenshot_20230403-101316.png](https://user-images.githubusercontent.com/1598041/229452194-55fa788b-0545-4665-bbc0-3bbc9d5eed9d.png)

Tanks again

**Comment by mudkipme** [comment]
Thanks for reporting.

I can't reproduce this issue myself. Could you reply with your current keyboard app and switch to another keyboard and try whether it's possible to reproduce this problem.

**Comment by bonnebulle** [comment]
Yep, you are right...
the "bug" was from my Android keyboard. 
I was using https://github.com/AnySoftKeyboard/AnySoftKeyboard
I just discovered https://github.com/Julow/Unexpected-Keyboard (and give it a try)

Thanks @mudkipme 
( quick reply, great job )
