### ISSUE TITLE
图片放大有bug

### ISSUE THREAD

**Issue by Lincest** [mudkipme/MoeMemosAndroid#68]
复现: 单击图片放大时，图片会闪一下然后消失

手机是realme neo2 android 13

**Comment by Lincest** [comment]
![Screenshot_2023-04-21-14-09-49-15_ce65f4715c7a7a11bce05c685360eaee](https://user-images.githubusercontent.com/43769667/233555382-0ec04170-0755-4060-a3b7-4685fd75852f.jpg)

![Screenshot_2023-04-21-14-10-41-05_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/43769667/233555396-f94f8140-efe3-41fb-a9c7-abf765f4d7d8.jpg)

**Comment by runforprogram** [comment]
OPPO的Color os Android 13同样现象,Logcat有错误 `MediaSyncManager        E  executeUrisSync uri is error !`
但是模拟器Android 13 没有问题.

**Comment by runforprogram** [comment]
看起来是因为`MoeMemosFileProvider`没有返回正确的type导致的兼容性问题,返回`image/jpeg`测试ok.已提[pr](https://github.com/mudkipme/MoeMemosAndroid/pull/82)
