### ISSUE TITLE
Implement checklists

### ISSUE THREAD

**Issue by tapionx** [mudkipme/MoeMemosAndroid#7]
The app currently does not support checklist, it would be really useful to support them for my grocery list 😁

![Screenshot_2022-11-22-21-50-27-20_ce65f4715c7a7a11bce05c685360eaee](https://user-images.githubusercontent.com/1826929/203418625-7688eea5-4085-4954-8168-5105b683c655.jpg)

**Comment by mudkipme** [comment]
Checklist is planned as part of Markdown support.  😄

**Comment by mudkipme** [comment]
0.3.0 is released with check list support! (Still needs a few hours for Google Play/F-Droid update)
