### ISSUE TITLE
The visibility button disappears.

### ISSUE THREAD

**Issue by bestruirui** [mudkipme/MoeMemosAndroid#72]
![Screenshot_2023-05-11-17-42-16-323_me mudkip moememos](https://github.com/mudkipme/MoeMemosAndroid/assets/89796393/54f1ca96-6405-44b8-924e-5f67fb332494)
It's the latest vision 0.6.1

**Comment by mudkipme** [comment]
It's a known issue fixed by #67 which will be included in next release.

You can also add a tag in any memos as a workaround.

**Comment by bestruirui** [comment]
thankyou
