### ISSUE TITLE
折叠帖子以节省手机屏幕空间

### ISSUE THREAD

**Issue by AgathonLi** [mudkipme/MoeMemosAndroid#75]
使用时发现，长文帖子在手机上观看时，会直接占据整个屏幕，向下拖动很久才能划到其他帖子，很不方便。

因此想到，能否将长帖子进行折叠？比如指定一个长度，超过该长度的都进行折叠，用户需要点击展开查看全文；或者点入帖子查看详情，才能看到全文。后一种实现方式好像更好，可以完全规避长文划不到头的问题，按返回键即可回到帖子列表页面。

**Comment by aholeye** [comment]
同样能否调整图片的展示，如果多图的话 缩小图片 并以一行最多3个排列

**Comment by aholeye** [comment]
[Screen_recording_20230821_200232.webm](https://github.com/mudkipme/MoeMemosAndroid/assets/26758630/6fbaf6a7-c954-4a6e-a2c9-53e234a5fdae)

**Comment by AgathonLi** [comment]
Nice! 给大佬点赞~
