### ISSUE TITLE
cannot click urls

### ISSUE THREAD

**Issue by 3291823** [mudkipme/MoeMemosAndroid#8]
It appears I cannot click URLs with the app. Forcing me to click edit then 'copy/paste' by hand. 
Please add this enhancement. TIA.

**Comment by mudkipme** [comment]
URL and link is planned as part of Markdown support. 😄

**Comment by mudkipme** [comment]
0.3.0 is released with URL support! (Still need a few hours for Google Play/F-Droid update)

**Comment by qrzbing** [comment]
Hi, I write a memo like:

``` markdown
Useful links

<https://regex101.com/> #regex
```

in Moe Memos. When I click the URL above, Moe Memos will crash. The version of Moe Memos is v0.5.3.

**Comment by qrzbing** [comment]
I find that if I change `<https://regex101.com/>` to `https://regex101.com/` (that is, remove the angle brackets won't cause crash).
