### ISSUE TITLE
Login fails with invalid access token on memos 0.13.2

### ISSUE THREAD

**Issue by jl-678** [mudkipme/MoeMemosAndroid#85]
Since upgrading to Memos 0.13.2, I cannot log into memos with the Moe Memos app. I always get an "Invalid access token" error. I am not sure if this is a Memos issue or a Moe Memos issue and so opened an issue in both places Note that I can access 0.13.2 via the web client with no issues and that things work normally when I roll back to 0.13.1.

I noticed that in the 0.13.2 changelog, they made some access token changes and am wondering if that is the issue.

Update: According to the memos team, the issue relates to API changes in memos that the Moe Memos team needs to implement. See this [closed issue](https://github.com/usememos/memos/issues/1882).

**Comment by mudkipme** [comment]
I'm investigating and hope to support the new version soon.

For now you can try logging in with Open API.

**Comment by jl-678** [comment]
Thank you!
