### ISSUE TITLE
无法登录，显示Not Found

### ISSUE THREAD

**Issue by 674830790** [mudkipme/MoeMemosAndroid#92]

**Comment by 674830790** [comment]
app版本  0.6.2 (17)

**Comment by mudkipme** [comment]
Please upgrade to Moe Memos 0.7.0.
https://github.com/mudkipme/MoeMemosAndroid/releases/tag/0.7.0

**Comment by 674830790** [comment]
> Please upgrade to Moe Memos 0.7.0. https://github.com/mudkipme/MoeMemosAndroid/releases/tag/0.7.0

非常感谢 我是从f-droid下载的，目前f-droid只更新到了0.6.2 我以为最新版就是0.6.2了
